=== AmeenSassi/redoneHW0/MovieActors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
    elementFormDefault="qualified"
    targetNamespace="http://sample"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="movies" type="sam:moviesType" xmlns:sam="http://sample"/>
  <xs:complexType name="moviesType">
    <xs:sequence>
      <xs:element type="sam:movieType" name="movie" maxOccurs="unbounded" xmlns:sam="http://sample"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="actorType">
    <xs:sequence>
      <xs:element name="Name">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                  <xs:minLength value="1"/>
              </xs:restriction>
          </xs:simpleType>
      </xs:element>
      <xs:element type="xs:date" name="DateOfBirth"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="actorsType">
    <xs:sequence>
      <xs:element type="sam:actorType" name="actor" maxOccurs="unbounded" xmlns:sam="http://sample"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="movieType">
    <xs:sequence>
      <xs:element name="Title">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                  <xs:minLength value="1"/>
              </xs:restriction>
          </xs:simpleType>
      </xs:element>
      <xs:element name="Year">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                    <xs:pattern value="\d\d\d\d"/>
            </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Genre">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Action" />
                <xs:enumeration value="Adventure" />
                <xs:enumeration value="Comedy" />
                <xs:enumeration value="Drama" />
                <xs:enumeration value="Fantasy" />
                <xs:enumeration value="Horror" />
                <xs:enumeration value="Mystery" />
                <xs:enumeration value="Thriller" />
                <xs:enumeration value="Western" />
            </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="sam:actorsType" name="actors" xmlns:sam="http://sample"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== AmeenSassi/redoneHW0/MovieActors.xml
<?xml version="1.0"?>
<movies
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://sample"
        xsi:schemaLocation="http://sample MovieActors.xsd">

    <movie>
        <Title>The Terminal</Title>
        <Year>1994</Year>
        <Genre>Drama</Genre>

        <actors>
            <actor>
                <Name>Tom Hanks</Name>
                <DateOfBirth>1956-08-09</DateOfBirth>
            </actor>

            <actor>
                <Name>Catherine Kenner</Name>
                <DateOfBirth>1959-03-23</DateOfBirth>
            </actor>
        </actors>
    </movie>

    <movie>
        <Title>Captain Phillips</Title>
        <Year>2013</Year>
        <Genre>Thriller</Genre>

        <actors>
            <actor>
                <Name>Tom Hanks</Name>
                <DateOfBirth>1956-08-09</DateOfBirth>
            </actor>
        </actors>
    </movie>
</movies>
